# https://github.com/imbatony/electorn-chinese-chess

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:

name: 发布 Release

permissions: write-all

jobs:
  build:
    name: Build Release & Upload Assets 2
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install
      - run: yarn run build:win
        env: 
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          
